name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: your-aws-region
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
       AWS_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
       
      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Tag Docker image
        run: docker tag your-image-name:latest aws-account-id.dkr.ecr.region.amazonaws.com/your-repository-name:latest

      - name: Push Docker image to ECR
        run: docker push aws-account-id.dkr.ecr.region.amazonaws.com/your-repository-name:latest

   
